path:
    logs: logs
    config: config
instances:
    dummy_server:
        starter:
            module: unogame.instances.d_server
            name: start_server
            params:
                ip: 192.168.56.1
                port: 5555
    dummy_client:
        starter:
            module: unogame.instances.d_client
            name: start_client
            params:
                width: 500
                height: 500
                caption: client
        player:
            module: unogame.game.player
            name: Player
            params:
                x: 50
                y: 50
                width: 100
                height: 100
                color: [0, 255, 0]
game:
    cards:
    rules: